spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: tuproyecto
    password: postupTupr0y3ct0!.co13
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true